FROM phusion/passenger-nodejs
LABEL maintainer="Juan Treminio <jtreminio@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# Upgrade Node
RUN apt-get update &&\
    apt-get install --only-upgrade nodejs &&\
    apt-get -y --purge autoremove &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/{man,doc}

RUN npm install yarn -g

RUN rm -f /etc/nginx/sites-enabled/default \
          /etc/service/nginx/down

ADD files/nginx-vhost.conf /etc/nginx/sites-enabled/default
